from __future__ import annotations

import io
import unittest
import zipfile

from main_app.services.pptx_export_service import PptxExportService


class TestPptxBrandedExportRegression(unittest.TestCase):
    @staticmethod
    def _slides() -> list[dict[str, object]]:
        return [
            {
                "title": "Executive Summary",
                "section": "Overview",
                "representation": "bullet",
                "bullets": [
                    "Focus on automation velocity.",
                    "Prioritize reliability and observability.",
                ],
            },
            {
                "title": "Implementation",
                "section": "Build",
                "representation": "bullet",
                "bullets": ["Explain integration details."],
                "code_snippet": "```python\nprint('hello world')\n```",
                "code_language": "python",
            },
        ]

    def test_template_list_contains_branded_key(self) -> None:
        service = PptxExportService()
        keys = {item.get("key") for item in service.list_templates()}
        self.assertIn("agentic_blocks_brand", keys)

    def test_branded_pptx_export_or_dependency_error(self) -> None:
        service = PptxExportService()
        pptx_bytes, error = service.build_pptx(
            topic="Agentic Architecture",
            slides=self._slides(),
            template_key="agentic_blocks_brand",
        )

        if pptx_bytes is None:
            self.assertIsNotNone(error)
            self.assertIn("python-pptx", str(error).lower())
            return

        self.assertIsNone(error)
        self.assertTrue(pptx_bytes.startswith(b"PK"))

        archive = zipfile.ZipFile(io.BytesIO(pptx_bytes))
        slide_xml_names = sorted(
            name for name in archive.namelist() if name.startswith("ppt/slides/slide") and name.endswith(".xml")
        )
        self.assertEqual(len(slide_xml_names), len(self._slides()) + 1)

        combined_xml = "".join(archive.read(name).decode("utf-8", errors="ignore") for name in slide_xml_names)
        self.assertIn("Generated by Knowledge App", combined_xml)
        self.assertIn("Code (python)", combined_xml)

    def test_branded_pdf_export_or_dependency_error(self) -> None:
        service = PptxExportService()
        pdf_bytes, error = service.build_pdf(
            topic="Agentic Architecture",
            slides=self._slides(),
            template_key="agentic_blocks_brand",
        )

        if pdf_bytes is None:
            self.assertIsNotNone(error)
            self.assertIn("reportlab", str(error).lower())
            return

        self.assertIsNone(error)
        self.assertTrue(pdf_bytes.startswith(b"%PDF"))
        page_markers = pdf_bytes.count(b"/Type /Page")
        self.assertGreaterEqual(page_markers, len(self._slides()) + 1)


if __name__ == "__main__":
    unittest.main()
