from __future__ import annotations

import unittest
from unittest.mock import patch

from main_app.services.pptx_export.design_tokens import apply_design_tokens, default_layout_presets
from main_app.services.pptx_export.models import BrandingTokens, PptxTemplateStyle, TypographyTokens


class TestPptxDesignTokens(unittest.TestCase):
    def test_apply_design_tokens_merges_defaults_and_footer_text(self) -> None:
        style = PptxTemplateStyle(
            key="test_style",
            title="Test Style",
            description="Token test style",
            font_name="Aptos",
            background_color=(255, 255, 255),
            accent_color=(1, 2, 3),
            title_color=(10, 11, 12),
            body_color=(20, 21, 22),
            section_chip_color=(30, 31, 32),
            section_chip_text_color=(40, 41, 42),
            code_panel_color=(50, 51, 52),
            code_text_color=(60, 61, 62),
            typography=TypographyTokens(
                title_font="Calibri",
                subtitle_font="Calibri",
                body_font="Calibri",
                caption_font="Calibri",
                code_font="Consolas",
            ),
            branding=BrandingTokens(footer_text=""),
            layout_presets={"body_box": (1.0, 1.0, 8.0, 4.0)},
        )

        with patch("main_app.services.pptx_export.design_tokens.discover_font_files", return_value={}):
            with patch("main_app.services.pptx_export.design_tokens.resolve_logo_path", return_value=""):
                resolved = apply_design_tokens(style)

        self.assertEqual(resolved.typography.title_font, "Aptos")
        self.assertEqual(resolved.typography.body_font, "Aptos")
        self.assertTrue(resolved.branding.footer_text.startswith("Generated by Knowledge App"))
        self.assertEqual(resolved.layout_presets["body_box"], (1.0, 1.0, 8.0, 4.0))
        for key in default_layout_presets():
            self.assertIn(key, resolved.layout_presets)

    def test_apply_design_tokens_uses_resolved_logo_paths(self) -> None:
        style = PptxTemplateStyle(
            key="logo_style",
            title="Logo Style",
            description="Logo path test",
            font_name="Calibri",
            background_color=(255, 255, 255),
            accent_color=(1, 2, 3),
            title_color=(10, 11, 12),
            body_color=(20, 21, 22),
            section_chip_color=(30, 31, 32),
            section_chip_text_color=(40, 41, 42),
            code_panel_color=(50, 51, 52),
            code_text_color=(60, 61, 62),
            branding=BrandingTokens(logo_path="relative-logo.png", footer_logo_path=""),
        )

        with patch("main_app.services.pptx_export.design_tokens.discover_font_files", return_value={}):
            with patch(
                "main_app.services.pptx_export.design_tokens.resolve_logo_path",
                side_effect=["/tmp/logo.png", "/tmp/footer.png"],
            ):
                resolved = apply_design_tokens(style)

        self.assertEqual(resolved.branding.logo_path, "/tmp/logo.png")
        self.assertEqual(resolved.branding.footer_logo_path, "/tmp/footer.png")


if __name__ == "__main__":
    unittest.main()
