from __future__ import annotations

from dataclasses import replace

from main_app.services.pptx_export.asset_loader import discover_font_files, resolve_logo_path
from main_app.services.pptx_export.models import (
    BrandingTokens,
    PptxTemplateStyle,
    ShapeTokens,
    SpacingTokens,
    TypographyTokens,
)


def default_layout_presets() -> dict[str, tuple[float, float, float, float]]:
    # Inches (x, y, width, height)
    return {
        "title_box": (0.7, 0.72, 11.9, 0.95),
        "section_chip_box": (9.35, 0.52, 3.0, 0.44),
        "body_box": (0.75, 1.85, 11.3, 4.95),
        "split_bullet_box": (0.72, 1.85, 5.92, 4.95),
        "split_code_box": (6.72, 1.72, 5.72, 5.23),
        "left_col_box": (0.8, 2.28, 5.2, 4.6),
        "right_col_box": (6.2, 2.28, 5.2, 4.6),
        "left_col_heading": (0.8, 1.86, 5.4, 0.45),
        "right_col_heading": (6.2, 1.86, 5.4, 0.45),
        "title_logo_box": (10.55, 0.34, 1.65, 0.65),
        "footer_logo_box": (10.95, 6.96, 1.0, 0.3),
        "footer_text_box": (0.72, 6.98, 8.95, 0.26),
    }


def apply_design_tokens(style: PptxTemplateStyle) -> PptxTemplateStyle:
    fonts = discover_font_files()
    resolved_logo = resolve_logo_path(style.branding.logo_path)
    resolved_footer_logo = resolve_logo_path(style.branding.footer_logo_path or resolved_logo)

    typography = style.typography
    if not typography:
        typography = TypographyTokens()
    if typography.title_font == "Calibri":
        typography = replace(typography, title_font=style.font_name)
    if typography.subtitle_font == "Calibri":
        typography = replace(typography, subtitle_font=style.font_name)
    if typography.body_font == "Calibri":
        typography = replace(typography, body_font=style.font_name)
    if typography.caption_font == "Calibri":
        typography = replace(typography, caption_font=style.font_name)
    if typography.code_font == "Consolas":
        typography = replace(typography, code_font="Consolas")

    spacing = style.spacing if style.spacing else SpacingTokens()
    shapes = style.shapes if style.shapes else ShapeTokens()
    branding = style.branding if style.branding else BrandingTokens()
    footer_text = branding.footer_text or f"Generated by Knowledge App | {style.title}"
    branding = replace(
        branding,
        logo_path=resolved_logo,
        footer_logo_path=resolved_footer_logo,
        footer_text=footer_text,
    )

    resolved_layout = dict(default_layout_presets())
    if style.layout_presets:
        resolved_layout.update(style.layout_presets)

    # If brand assets exist, prefer stable family names used by builders.
    if fonts:
        typography = replace(
            typography,
            title_font=typography.title_font or style.font_name,
            subtitle_font=typography.subtitle_font or style.font_name,
            body_font=typography.body_font or style.font_name,
            caption_font=typography.caption_font or style.font_name,
            code_font=typography.code_font or "Consolas",
        )

    return replace(
        style,
        typography=typography,
        spacing=spacing,
        shapes=shapes,
        branding=branding,
        layout_presets=resolved_layout,
    )

